---
- name: "build containers with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running containers
      shell: |
        docker stop my-app-main
        docker stop my-app-dev
      ignore_errors: yes

    - name: remove stopped container
      shell: |
        docker rm my-app-main
        docker rm my-app-dev
      ignore_errors: yes

    - name: Run main container
      command: docker run -d --name my-app-main -p 3000:3000 hassdx/cicd-web-container:main

    - name: Run dev container
      command: docker run -d --name my-app-dev -p 3001:3000 hassdx/cicd-web-container:dev
  
